### PR TITLE
Fix incorrect dealing with offset sub-frames

### PR DESCRIPTION
**Pull request by Jimbly**
gifwrap fails to correctly decode `test/fixtures/rnaples-offsets-public.gif` included in its tests.  I threw together a [simple test that combines all frames into one image with Jimp](https://gist.github.com/Jimbly/ea88b0e96817a30ad8a5c230a3776590).

Erroneous results:
[out_bad_128](https://jimbly.github.io/gifwrap/out_bad.png)

Expected results (after applying fix):
[out_good_128](https://jimbly.github.io/gifwrap/out_good.png)

omggif's `decodeAndBlitFrameRGBA` blits the entire frame, not just the sub-region, so, in order to keep the GifCode API the same, we must contract the buffer, skipping all of the empty space.

An alternative solution would be to simply set `info.[width/height] = reader.[width/height]; info.[x/y] = 0`, which would be slightly faster in here (but cause clients to be slower, as they have to blend the whole image).

Better yet would be to fix omggif (or use a different library) to allow returning just the sub-section, however I looked into decodeAndblitFrameRGBA and it gets pretty complicated due to interlacing and stuff.

But, for a quick fix, this'll do.

### CODE REVIEW

**Comment by devinivy** [comment]
I can't verify the fix itself, but this solves similar problems I was having with an animated gif as well.

**Comment by Jimbly** [comment]
Yeah, without this fix, I seem to recall that any animated GIFs that animated a sub-frame (don't replace the entire frame each time) won't work.

**Comment by devinivy** [comment]
Ah!  Yeah, that is consistent with what I've seen.

**Comment by jtlapp** [comment]
Thank you sooo much for finding and fixing this problem. For now, we'll call it expected interface protocol for Omggif. I also added a test to confirm expected behavior.

**Comment by Jimbly** [comment]
Glad to help, thanks for merging!

**Pull request merged**
